### ISSUE TITLE
Does this plugin also restrict / influence the tile loading queue of OSD?

### ISSUE THREAD

**Issue by jetic83** [picturae/OpenSeadragonZoomLevels#1]
OSD usually loads tiles in background, e.g. also of different zoom levels than currently shown.
Would this plugin cause OSD to only load those relevant zoom levels that I specify (and never load tiles from zoom levels that I anyway don't want to display), or would it let OSD load everything it wants and then just restrict the displayed zoom to those specified levels?

**Comment by MindFreeze** [comment]
No. Only the displaying is restricted. If you skip a few levels OSD might
skip loading some but the plugin does not directly influence loading.
